cloud: {}
counter: {}
# history: {} # Disable history
input_boolean: {}
input_datetime: {}
input_number: {}
input_select: {}
input_text: {}
# logbook: {} # Disable logbook
map: {}
# media_source: {} # Disable Media Browser
mobile_app: {}
person: {}
ssdp: {}
sun: {}
system_health: {}
tag: {}
timer: {}
updater: {}
webhook: {}
# zeroconf: {} # Does not work since not using host networking
zone: {}

# Enable access over reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    # "webproxy" Docker network
    - 172.18.0.0/16

google_assistant:
  project_id: klubod-home-assistant
  service_account: !include service_account.json
  report_state: true
  expose_by_default: false
  entity_config:
    light.ledstrip:
      name: LED strip

# Honeywell Lyric
lyric:
  client_id: !secret lyric_id
  client_secret: !secret lyric_secret

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes

sensor:
  # Solar Inverter
  - platform: sems
    station_id: !secret sems_station_id
    username: !secret sems_username
    password: !secret sems_password
    scan_interval: 60

  # Creating entities from single sems entity
  - platform: template
    sensors:
      pv_outputpower:
        value_template: '{{ states.sensor.solar_inverter.attributes.outputpower / 1000 }}'
        unit_of_measurement: 'kW'
      pv_temperature:
        value_template: '{{ states.sensor.solar_inverter.attributes.tempperature }}'
        unit_of_measurement: 'C'
      pv_eday:
        value_template: '{{ states.sensor.solar_inverter.attributes.eday }}'
        unit_of_measurement: 'kWh'
